# version of docker-compose
version: '3.9'
# 'services' are equivalent to 'containers'
services:
  redis-server:
    # Use Docker Hub base image 'redis:alpine' 
    image: redis:alpine
    #command: redis-server
  web:
    restart: on-failure
    build: ./HelloWorldChat
    ports:
      - '3000:3000'
